// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"tmp/pragmatic-cases/ent/getting-started-with-versioned-migrations/ent/animal"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnimalCreate is the builder for creating a Animal entity.
type AnimalCreate struct {
	config
	mutation *AnimalMutation
	hooks    []Hook
}

// SetSpecies sets the "species" field.
func (ac *AnimalCreate) SetSpecies(s string) *AnimalCreate {
	ac.mutation.SetSpecies(s)
	return ac
}

// SetAge sets the "age" field.
func (ac *AnimalCreate) SetAge(i int) *AnimalCreate {
	ac.mutation.SetAge(i)
	return ac
}

// SetName sets the "name" field.
func (ac *AnimalCreate) SetName(s string) *AnimalCreate {
	ac.mutation.SetName(s)
	return ac
}

// Mutation returns the AnimalMutation object of the builder.
func (ac *AnimalCreate) Mutation() *AnimalMutation {
	return ac.mutation
}

// Save creates the Animal in the database.
func (ac *AnimalCreate) Save(ctx context.Context) (*Animal, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AnimalCreate) SaveX(ctx context.Context) *Animal {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AnimalCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AnimalCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AnimalCreate) check() error {
	if _, ok := ac.mutation.Species(); !ok {
		return &ValidationError{Name: "species", err: errors.New(`ent: missing required field "Animal.species"`)}
	}
	if _, ok := ac.mutation.Age(); !ok {
		return &ValidationError{Name: "age", err: errors.New(`ent: missing required field "Animal.age"`)}
	}
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Animal.name"`)}
	}
	return nil
}

func (ac *AnimalCreate) sqlSave(ctx context.Context) (*Animal, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AnimalCreate) createSpec() (*Animal, *sqlgraph.CreateSpec) {
	var (
		_node = &Animal{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(animal.Table, sqlgraph.NewFieldSpec(animal.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.Species(); ok {
		_spec.SetField(animal.FieldSpecies, field.TypeString, value)
		_node.Species = value
	}
	if value, ok := ac.mutation.Age(); ok {
		_spec.SetField(animal.FieldAge, field.TypeInt, value)
		_node.Age = value
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(animal.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// AnimalCreateBulk is the builder for creating many Animal entities in bulk.
type AnimalCreateBulk struct {
	config
	err      error
	builders []*AnimalCreate
}

// Save creates the Animal entities in the database.
func (acb *AnimalCreateBulk) Save(ctx context.Context) ([]*Animal, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Animal, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnimalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AnimalCreateBulk) SaveX(ctx context.Context) []*Animal {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AnimalCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AnimalCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
