// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"tmp/pragmatic-cases/ent/getting-started-with-versioned-migrations/ent/animal"
	"tmp/pragmatic-cases/ent/getting-started-with-versioned-migrations/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnimalDelete is the builder for deleting a Animal entity.
type AnimalDelete struct {
	config
	hooks    []Hook
	mutation *AnimalMutation
}

// Where appends a list predicates to the AnimalDelete builder.
func (ad *AnimalDelete) Where(ps ...predicate.Animal) *AnimalDelete {
	ad.mutation.Where(ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *AnimalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ad.sqlExec, ad.mutation, ad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *AnimalDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *AnimalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(animal.Table, sqlgraph.NewFieldSpec(animal.FieldID, field.TypeInt))
	if ps := ad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ad.mutation.done = true
	return affected, err
}

// AnimalDeleteOne is the builder for deleting a single Animal entity.
type AnimalDeleteOne struct {
	ad *AnimalDelete
}

// Where appends a list predicates to the AnimalDelete builder.
func (ado *AnimalDeleteOne) Where(ps ...predicate.Animal) *AnimalDeleteOne {
	ado.ad.mutation.Where(ps...)
	return ado
}

// Exec executes the deletion query.
func (ado *AnimalDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{animal.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *AnimalDeleteOne) ExecX(ctx context.Context) {
	if err := ado.Exec(ctx); err != nil {
		panic(err)
	}
}
