// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"tmp/pragmatic-cases/ent/simple-example/ent/itemcategory"

	"entgo.io/ent/dialect/sql"
)

// ItemCategory is the model entity for the ItemCategory schema.
type ItemCategory struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ItemCategory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case itemcategory.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ItemCategory", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ItemCategory fields.
func (ic *ItemCategory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case itemcategory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ic.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this ItemCategory.
// Note that you need to call ItemCategory.Unwrap() before calling this method if this ItemCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (ic *ItemCategory) Update() *ItemCategoryUpdateOne {
	return (&ItemCategoryClient{config: ic.config}).UpdateOne(ic)
}

// Unwrap unwraps the ItemCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ic *ItemCategory) Unwrap() *ItemCategory {
	_tx, ok := ic.config.driver.(*txDriver)
	if !ok {
		panic("ent: ItemCategory is not a transactional entity")
	}
	ic.config.driver = _tx.drv
	return ic
}

// String implements the fmt.Stringer.
func (ic *ItemCategory) String() string {
	var builder strings.Builder
	builder.WriteString("ItemCategory(")
	builder.WriteString(fmt.Sprintf("id=%v", ic.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ItemCategories is a parsable slice of ItemCategory.
type ItemCategories []*ItemCategory

func (ic ItemCategories) config(cfg config) {
	for _i := range ic {
		ic[_i].config = cfg
	}
}
