// Code generated by ent, DO NOT EDIT.

package itemcategory

const (
	// Label holds the string label denoting the itemcategory type in the database.
	Label = "item_category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the itemcategory in the database.
	Table = "item_categories"
)

// Columns holds all SQL columns for itemcategory fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
