-- Create "animals" table
CREATE TABLE "animals" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "species" character varying NOT NULL, "age" bigint NOT NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
